.\" vim: set syntax=nroff :
.Dd COMMIT
.Dt irccat 1
.Os
.Sh NAME
.Nm irccat
.Nd mIRC formatting code aware
.Xr cat 1
.Sh SYNOPSIS
.Nm
.Op Ar FILES...
.Sh DESCRIPTION
.Nm
concatenates input files and converts them to ANSI-formatted output.

If '-' is passed as a file,
.Nm
will read from standard input.
.Sh SEE ALSO
.Xr hirc 1
.Sh AUTHOR
.An hhvn Aq Mt dev@hhvn.uk
